baseURL = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "posts"
  defaultTheme = "light"
  showMenuItems = 2
  showReadingTime = false

  [[params.social]]
    name = "github"
    url  = "https://github.com/oldani"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ordanisanchez"

  [[params.social]]
    name = "email"
    url  = "mailto:ordanisanchez@gmail.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://linkedin.com/in/ordanis/"

[languages]
  [languages.en]
    title = "Ordanis Sanchez"
    homeSubtitle = "A Python Backend Developer"
    subtitle = "Python Dev"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "$ cd /home"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
      
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
